### ISSUE TITLE
HD Skins (128 x 128) aren't working

### ISSUE THREAD

**Issue by IkyMax** [NickAcPT/nmsr-rs#9] opened 2024-02-20 22:55 UTC
Trying to get HD skins result in renderers like these
![095dd34a2a54453e8a737d30c8ccb1a3](https://github.com/NickAcPT/nmsr-rs/assets/112127881/96e5a752-bdf8-4789-979d-9997966c73f3)

**Comment by NickAcPT** [comment] 2024-03-02 15:41
This issue has been fixed by commit https://github.com/NickAcPT/ears-rs/commit/e621000b10b7cd6bc5ca83291c692d89c2b72b50.

Turns out nmsr wasn't directly at fault for the borked skins! The issue was instead caused by the legacy skin upgrader in `ears-rs` which has now been fixed to handle images with higher resolutions.

**Closed as completed by NickAcPT** 2024-03-02 15:41 UTC
